KEEP_ORIGINALS


parameter Radius = 0.5
parameter CylHt = Radius*3
parameter LiqHt = Radius
parameter LenStem = Radius*4
parameter CAsl = 45 // contact angle between solid sphere and liquid
#define WALLT (-cos(CAsl*pi/180))

// calculate merging point of two cylinder
parameter ang = 60*pi/180
parameter lenC = sqrt(Radius^2 + Radius^2*(tan(ang))^2)
parameter posx_merge = (lenC - Radius)/tan(ang)
parameter posy_merge = Radius

// calculate properties of rotated cylinder
parameter cyl2x = LenStem*0.5*sin(ang*0.5)
parameter cyl2y = LenStem*0.5*cos(ang*0.5)
parameter endx = Radius*sin(ang)
parameter endy = Radius*cos(ang)

// hexagon center location
parameter HexCx = LenStem*0.5
parameter HexCy = LenStem*sqrt(3)/2


////////////////

constraint 1 convex // cylinder 1 x-y
formula: x^2 + (z-Radius-CylHt)^2 = Radius^2


constraint 2 // right boundary
formula: y = LenStem*0.5
energy:
e1: 0
e2: 0
e3: 0


constraint 3 // top boundary
formula: x = 0
energy:
e1: 0
e2: 0
e3: 0

constraint 4 // rotated edge boundary
formula: y = (((HexCx-posx_merge)/(HexCy-posy_merge))*(x - posy_merge)) + posx_merge
energy:
e1: 0
e2: 0
e3: 0

constraint 5 nonnegative // z >= 0
formula: z = 0

constraint 6 convex // rotated cylinder using coordinate transform
formula: (x*cos(ang) + y*sin(ang))^2 + (z-Radius-CylHt)^2 = Radius^2

constraint 7 // rotated cylinder boundary
formula: y = ((HexCx-(endx-cyl2x))/(HexCy-(endy+cyl2y)))*(x-(endy+cyl2y)) + endx-cyl2x
energy:
e1: 0
e2: 0
e3: 0

constraint 8 // top boundary rotated cylinder
formula: y = -(cyl2x/cyl2y)*x
energy:
e1: 0
e2: 0
e3: 0


///////////////////////////////////////////////////////////////
vertices:
// upside cyl 1
1 posy_merge posx_merge LiqHt+CylHt constraint 1 4 5
2 Radius LenStem*0.5 LiqHt+CylHt constraint 1 2 5
3 0 0 CylHt+Radius*2 constraint 1 3 4
4 0 LenStem*0.5 CylHt+Radius*2 constraint 1 2 3


// underside
5 0 LenStem*0.5 CylHt constraint 1 2 3
6 0 0 CylHt constraint 1 3 4


// center
7 HexCy HexCx LiqHt+CylHt constraint 2 4 5

// halfway to center
8 posy_merge+Radius LenStem*0.25 LiqHt+CylHt constraint 4 5

// upside cyl 2
9 endy+cyl2y endx-cyl2x LiqHt+CylHt constraint 6 7 5
10 cyl2y -cyl2x Radius*2+CylHt constraint 6 7 8

// downside cyl 2
11 cyl2y -cyl2x CylHt constraint 6 7 8

// bott
12 0 0 0 FIXED
13 cyl2y -cyl2x 0 FIXED
14 0 LenStem*0.5 0 FIXED
15 HexCy HexCx 0 FIXED

 
edges:
1 1 2 constraint 1
// upside
2 1 3 constraint 4 1
3 2 4 constraint 2 1
4 3 4 constraint 1 3

// underside
5 1 6 constraint 4 1
6 2 5 constraint 2 1
7 6 5 constraint 1 3

// liq surface
8 1 8 
9 8 7 
10 7 2 constraint 2
11 8 2
17 8 9
18 9 7 constraint 7

// cyl 2
// upside
12 1 9 constraint 6
13 3 10 constraint 6 8
14 9 10 constraint 6 7

// downside
15 9 11 constraint 6 7
16 11 6 constraint 6 8

19 12 14 fixed no_refine
20 14 15 fixed no_refine
21 15 13 fixed no_refine
22 13 12 fixed no_refine

faces:
// cyl 1
1 1 3 -4 -2 constraint 1 density 0 color lightred
2 7 -6 -1 5 constraint 1 tension WALLT color lightred
// cyl 2
5 2 13 -14 -12 constraint 6 density 0 color lightred
6 12 15 16 -5 constraint 6 tension WALLT color lightred

3 11 -1 8 constraint 5 tension 1 color blue
4 9 10 -11 constraint 5 tension 1 color blue
7 18 -9 17 constraint 5 tension 1 color blue
8 -17 -8 12 constraint 5 tension 1 color blue 

/// base for dislay
9 -22 -21 -20 -19 color lightred fixed no_refine

bodies:
1 -2 -6 3 4 7 8 pressure -1.40

read
stl := { 
   local mag,inx;
   printf "solid\n" >> "C:/evolver2/stlmodel.txt";
   foreach facet ff do
   { mag := sqrt(ff.x^2+ff.y^2+ff.z^2);
     printf "facet normal %f %f %f\n",ff.x/mag,ff.y/mag,ff.z/mag >> "C:/evolver2/stlmodel.txt";
     printf "   outer loop\n" >> "C:/evolver2/stlmodel.txt";
     for ( inx := 1 ; inx <= 3 ; inx += 1 )
       printf "     vertex %f %f %f\n",ff.vertex[inx].x,ff.vertex[inx].y,
             ff.vertex[inx].z >> "C:/evolver2/stlmodel.txt";
     printf "   endloop\n" >> "C:/evolver2/stlmodel.txt";
     printf "  endfacet\n">> "C:/evolver2/stlmodel.txt";
   };
   printf "endsolid\n" >> "C:/evolver2/stlmodel.txt";
}

Init := {r 3; V 20; u 2; V 20}
Run1  := {V 20; u 2; V 20; g 20}
Run2 := {V 20; u 2; V 20; g 40}

Run_ALL := {Init; Run1 40; Run2 20; r; Run1 20; Run2 50}

liq_thik3:=
{ printf "ID	x	y	z\n" >> "C:/evolver2/liq_thik.txt";
for (ii:=1; ii<=vertex_count;ii+=1) if (vertex[ii] on_constraint 5) then printf "%f %f %f %f \n", 
vertex[ii].id, vertex[ii].x, vertex[ii].y, vertex[ii].z>> "C:/evolver2/liq_thik.txt";}
